# Generated by Django 6.0.4 on 2026-04-30 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Имя (Компания)"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                (
                    "message",
                    models.TextField(
                        blank=True, null=True, verbose_name="Адрес или сообщение"
                    ),
                ),
            ],
            options={
                "verbose_name": "Обратная связь",
                "verbose_name_plural": "Обратные связи",
                "ordering": ("-id",),
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="photos/", verbose_name="Фотография"
            ),
        ),
    ]
